[package]
name = "slice_ops"
version = "0.1.7"
edition = "2021"
license = "MIT"
description = "A selection of useful slice operations that run at compile-time"
repository = "https://github.com/sigurd4/slice_ops"
keywords = ["slice", "const", "util", "ops"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

[dependencies]
moddef = "0.2.2"
slice_trait = "0.1.0"