moddef::moddef!(
    flat(pub) mod {
        add_assign,
        argminmax,
        argreduce,
        bitand_assign,
        bitor_assign,
        bitxor_assign,
        differentiate,
        div_assign,
        find,
        integrate,
        mul_assign,
        neg_assign,
        not_assign,
        permute,
        rem_assign,
        shift,
        shl_assign,
        shr_assign,
        split,
        spread,
        sub_assign,
        trim,
        visit
    }
);